### ISSUE TITLE
how to see the available flow's for a process 

### ISSUE THREAD

**Issue by anandrajB** [ramwin/viewflow-rest#1]
how to see the available flow's for a process

**Comment by ramwin** [comment]
Sorry for the late reply. Currently this project doesn't support this function. But this can be easily done by add some snippet in `viewflow_rest/flows.py`  `FlowMetaClass.__new__` function

    class FlowMetaClass(type):
        def __new__(cls, class_name, bases, attrs, **kwargs):
            ...
            process_class = attrs.getattr("process_class", None)
            if process_class:
                if not hasattr(process_class, "registered_flows"):
                    process_class.registered_flows = {}
                process_class.registered_flows.add(new_class)
            return new_class

You can clone this project and apply the code above. A PR is welcomed.

**Comment by ramwin** [comment]
I have created a new release 1.2.0, now you can see the available flow's for a process. [feat: add registered_flows to the process model ](https://github.com/ramwin/viewflow-rest/commit/aea49edc0353d5444c12dfabd6dce446a2336a4d)

**Comment by anandrajB** [comment]
support for django==4.0 ?
