### ISSUE TITLE
How Can Assign Task

### ISSUE THREAD

**Issue by m3r3lin** [ramwin/viewflow-rest#4]
Hello , How Can Assign Task? I Want Assign a Task to some user without use group , only with select user or users in previous task , and only selected user can do task

**Comment by ramwin** [comment]
The `nodes.View` can accept the `viewclass` parameter. You can add create your own viewclass or permissionclass and use it in the flow class. E.g.

```
from viewflow_rest import flows, nodes

class MyFlow(flows.Flow):
    ...some previous flow...

    my_node = nodes.View(
        viewclaass=<your custom APIView>,   # use custom apiview
        permission_classes=[<your custom perssion>,]  # or use custom permission_class
    ).next(...)
   ...some following flow...
```

**Comment by m3r3lin** [comment]
I use https://github.com/dfunckt/django-rules and combine with this package

in mixins:
`class PermissionMixin(object):

    def __init__(self, *args, **kwargs):
        self._owner_group = None
        self._permissions = None
        super().__init__(*args, **kwargs)

    def Permission(self, group=None , permissions = None):
        self._owner_group = group
        self._permissions = permissions
        return self `

in nodes:

`def check_permission(_owner_group, _permissions, user) -> bool:
 
    if not _owner_group and not bool(_permissions):
        return True
    if not user:
        return False
    if isinstance(_owner_group, str):
        _owner_group = Group.objects.get(name=_owner_group)

    return (user in _owner_group.user_set.all() if _owner_group else False) or (
        any([rules.test_rule(permission, user) for permission in _permissions])) `

change this def in Start node and other node :

`    def can_execute(self, user, task=None):
        return check_permission(self._owner_group, self._permissions, user)`
