### ISSUE TITLE
how start one flow with code?

### ISSUE THREAD

**Issue by m3r3lin** [ramwin/viewflow-rest#6]
how can start one process with code? or how can execute one task with code and jump to the next task?

**Comment by ramwin** [comment]
the answer for second question can been seen [here](https://github.com/ramwin/viewflow-rest#faq)

**Comment by ramwin** [comment]
To start one process with code, you can call the start activation like [this code](https://github.com/ramwin/viewflow-rest/blob/main/viewflow_rest/views.py#L35)

**Comment by m3r3lin** [comment]
TNX
